In [1]:
# 1-4. Pandas 설치
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas", "openpyxl"])

0

In [2]:
import pandas as pd

scores = pd.Series([85, 92, 78, 96, 88])
print(scores)
# 0    85
# 1    92
# 2    78
# 3    96
# 4    88

# 인덱스를 직접 지정할 수도 있습니다
scores = pd.Series([85, 92, 78], index=["철수", "영희", "민준"])
print(scores["영희"])  # 92

0    85
1    92
2    78
3    96
4    88
dtype: int64
92

In [3]:
# DataFrame — 2차원 데이터
data = {
    "이름":  ["철수", "영희", "민준"],
    "나이":  [25, 28, 23],
    "점수":  [85, 92, 78]
}

df = pd.DataFrame(data)
print(df)
#    이름  나이  점수
# 0  철수   25   85
# 1  영희   28   92
# 2  민준   23   78

   이름  나이  점수
0  철수  25  85
1  영희  28  92
2  민준  23  78

In [4]:
# 2-3. Series와 DataFrame의 관계

# DataFrame에서 열 하나를 꺼내면 Series가 됩니다
print(type(df["점수"]))  # <class 'pandas.core.series.Series'>
print(df["점수"])
# 0    85
# 1    92
# 2    78

<class 'pandas.core.series.Series'>
0    85
1    92
2    78
Name: 점수, dtype: int64

In [5]:
# 3-1. CSV 파일 불러오기
df = pd.read_csv("data.csv")

# 자주 쓰는 옵션
df = pd.read_csv("data.csv", encoding="utf-8")      # 한글 파일
df = pd.read_csv("data.csv", index_col=0)           # 첫 열을 인덱스로
df = pd.read_csv("data.csv", nrows=100)             # 앞 100행만

In [6]:
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl"])

0

In [7]:
# 3-2. 엑셀 파일 불러오기

df = pd.read_excel("data.xlsx", sheet_name="직원정보")
print(df)

        사번   이름    부서  직급         입사일  연봉(만원) 평가등급
0   EMP001  김민준   개발팀  선임  2020-03-15    5200    A
1   EMP002  이소연  마케팅팀  책임  2017-07-01    6100   A+
2   EMP003  박지훈   개발팀  수석  2012-01-10    7800    S
3   EMP004  최유나  디자인팀  선임  2019-09-20    4900   B+
4   EMP005  정태현   영업팀  사원  2023-02-01    3600    A
5   EMP006  한은지   개발팀  책임  2015-05-15    6500   A+
6   EMP007  강동혁  경영지원  수석  2008-11-01    8200    A
7   EMP008  윤세린  마케팅팀  선임  2021-04-10    4500   B+
8   EMP009  임준우   개발팀  책임  2016-08-20    5800    A
9   EMP010  신하영  디자인팀  사원  2022-06-01    3800    A
10  EMP011  오승민  경영지원  책임  2013-03-15    7000   B+
11  EMP012  황지연   영업팀  선임  2018-12-01    5100   A+

In [8]:
# 3-3. 데이터 기본 확인

df.head()       # 상위 5행 출력 (기본값)
df.tail(3)      # 하위 3행 출력
df.info()       # 열 이름, 데이터 타입, 결측값 여부
df.describe()   # 수치형 열의 기초 통계 (평균, 표준편차, 최솟값 등)
df.shape        # (행 수, 열 수) 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사번      12 non-null     object
 1   이름      12 non-null     object
 2   부서      12 non-null     object
 3   직급      12 non-null     object
 4   입사일     12 non-null     object
 5   연봉(만원)  12 non-null     int64
 6   평가등급    12 non-null     object
dtypes: int64(1), object(6)
memory usage: 800.0+ bytes

(12, 7)

In [9]:
# 4-1. 열(column) 선택하기

# 열 하나 선택 → Series 반환
df["이름"]

# 열 여러 개 선택 → DataFrame 반환
df[["이름", "직급"]]

# 열 목록 확인
df.columns

Index(['사번', '이름', '부서', '직급', '입사일', '연봉(만원)', '평가등급'], dtype='object')

In [10]:
#  행(row) 선택 — loc vs iloc

# loc — 인덱스 이름으로 선택
df.loc[0]           # 인덱스가 0인 행
df.loc[0:2]         # 인덱스 0~2행 (끝 포함)
df.loc[0, "평가등급"]   # 0행의 점수 열

# iloc — 순서(정수)로 선택
df.iloc[0]          # 첫 번째 행
df.iloc[0:2]        # 0~1행 (끝 미포함, Python 슬라이싱 방식)
df.iloc[0, 2]       # 0행 2번째 열

'개발팀'

In [11]:
# 4-3. 조건으로 필터링하기

# 연봉이 6000 이상인 행만
df[df["연봉(만원)"] >= 6000]

# 부서가 "개발팀"이고 연봉이 5000 이상인 행
df[(df["부서"] == "개발팀") & (df["연봉(만원)"] >= 5000)]

# 이름이 "김민준"인 행
df[df["이름"] == "김민준"]

       사번   이름   부서  직급         입사일  연봉(만원) 평가등급
0  EMP001  김민준  개발팀  선임  2020-03-15    5200    A

In [12]:
# 4-4. 정렬하기
df.sort_values("연봉(만원)", ascending=False)  # 연봉 내림차순
df.sort_values(["부서", "연봉(만원)"])          # 부서 → 연봉 순으로 정렬

        사번   이름    부서  직급         입사일  연봉(만원) 평가등급
0   EMP001  김민준   개발팀  선임  2020-03-15    5200    A
8   EMP009  임준우   개발팀  책임  2016-08-20    5800    A
5   EMP006  한은지   개발팀  책임  2015-05-15    6500   A+
2   EMP003  박지훈   개발팀  수석  2012-01-10    7800    S
10  EMP011  오승민  경영지원  책임  2013-03-15    7000   B+
6   EMP007  강동혁  경영지원  수석  2008-11-01    8200    A
9   EMP010  신하영  디자인팀  사원  2022-06-01    3800    A
3   EMP004  최유나  디자인팀  선임  2019-09-20    4900   B+
7   EMP008  윤세린  마케팅팀  선임  2021-04-10    4500   B+
1   EMP002  이소연  마케팅팀  책임  2017-07-01    6100   A+
4   EMP005  정태현   영업팀  사원  2023-02-01    3600    A
11  EMP012  황지연   영업팀  선임  2018-12-01    5100   A+

In [13]:
# 5-1. 결측값(NaN) 처리

df.isnull()           # 각 셀의 결측 여부 (True/False)
df.isnull().sum()     # 열별 결측값 개수

# 결측값 제거
df.dropna()           # 결측값 있는 행 전체 삭제
df.dropna(axis=1)     # 결측값 있는 열 전체 삭제

# 결측값 채우기
df.fillna(0)               # 모든 결측값을 0으로
df["연봉(만원)"].fillna(df["연봉(만원)"].mean())  # 평균값으로 채우기

0     5200
1     6100
2     7800
3     4900
4     3600
5     6500
6     8200
7     4500
8     5800
9     3800
10    7000
11    5100
Name: 연봉(만원), dtype: int64

In [14]:
# 5-2. 중복 데이터 제거
df.duplicated()       # 중복 행 확인
df.drop_duplicates()  # 중복 행 제거

        사번   이름    부서  직급         입사일  연봉(만원) 평가등급
0   EMP001  김민준   개발팀  선임  2020-03-15    5200    A
1   EMP002  이소연  마케팅팀  책임  2017-07-01    6100   A+
2   EMP003  박지훈   개발팀  수석  2012-01-10    7800    S
3   EMP004  최유나  디자인팀  선임  2019-09-20    4900   B+
4   EMP005  정태현   영업팀  사원  2023-02-01    3600    A
5   EMP006  한은지   개발팀  책임  2015-05-15    6500   A+
6   EMP007  강동혁  경영지원  수석  2008-11-01    8200    A
7   EMP008  윤세린  마케팅팀  선임  2021-04-10    4500   B+
8   EMP009  임준우   개발팀  책임  2016-08-20    5800    A
9   EMP010  신하영  디자인팀  사원  2022-06-01    3800    A
10  EMP011  오승민  경영지원  책임  2013-03-15    7000   B+
11  EMP012  황지연   영업팀  선임  2018-12-01    5100   A+

In [15]:
# 5-3. 데이터 타입 변환
df.dtypes                                      # 각 열의 데이터 타입 확인
df["연봉(만원)"] = df["연봉(만원)"].astype(float)  # 정수 → 실수
df["사번"] = df["사번"].astype(str)                # 문자 확인

In [16]:
# 5-4. 열 조작

# 열 이름 변경
df.rename(columns={"연봉(만원)": "salary", "이름": "name"}, inplace=True)

# 새 열 추가
df["고연봉"] = df["salary"] >= 6000

# 열 삭제
df.drop(columns=["고연봉"], inplace=True)

In [17]:
# 6-1. 기본 통계
df["salary"].sum()    # 합계
df["salary"].mean()   # 평균
df["salary"].count()  # 개수 (결측값 제외)
df["salary"].max()    # 최댓값
df["salary"].min()    # 최솟값

np.float64(3600.0)

In [18]:
# 6-2. 그룹별 분석 — groupby

# 부서별 평균 연봉
df.groupby("부서")["salary"].mean()

# 부서별 여러 통계 한 번에
df.groupby("부서")["salary"].agg(["mean", "max", "count"])

        mean     max  count
부서
개발팀   6325.0  7800.0      4
경영지원  7600.0  8200.0      2
디자인팀  4350.0  4900.0      2
마케팅팀  5300.0  6100.0      2
영업팀   4350.0  5100.0      2

In [19]:
# 6-3. 피벗 테이블

df.pivot_table(values="salary", index="부서", columns="직급", aggfunc="mean")

직급        사원      선임      수석      책임
부서
개발팀      NaN  5200.0  7800.0  6150.0
경영지원     NaN     NaN  8200.0  7000.0
디자인팀  3800.0  4900.0     NaN     NaN
마케팅팀     NaN  4500.0     NaN  6100.0
영업팀   3600.0  5100.0     NaN     NaN

In [20]:
# 7-1. DataFrame을 NumPy 배열로 변환하기

# 방법 1
array = df.values

# 방법 2 (권장)
array = df.to_numpy()

print(type(array))   # <class 'numpy.ndarray'>
print(array.shape)   # (행 수, 열 수)

<class 'numpy.ndarray'>
(12, 7)

In [21]:
# 7-2. 피처(X)와 라벨(y) 분리하기 — data.csv 활용

df2 = pd.read_csv("data.csv")

# salary를 예측하는 모델을 만든다고 가정
X = df2[["age", "years_exp", "satisfaction"]].to_numpy()
y = df2["salary"].to_numpy()

print("X shape:", X.shape)
print(X[:5])

print("\ny shape:", y.shape)
print(y[:5])

X shape: (20, 3)
[[28.   3.   4.2]
 [35.   8.   3.8]
 [42.  15.   4.5]
 [31.   5.   4. ]
 [26.   2.   3.5]]

y shape: (20,)
[4500 5200 6800 4800 3900]